/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.edu.agh.to1.dice;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import pl.edu.agh.to1.dice.logic.DiceGame;

/**
 *
 * @author milosz
 */
public class DiceGUI extends javax.swing.JFrame{
    
    
//    private BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(App.getGuiToGameOutput()));
//    private BufferedReader br = new BufferedReader(new InputStreamReader(App.getGameToGuiInput()));
    
    /**
     * Creates new form DiceGUI
     */
    public DiceGUI() {
        initComponents();
        
        App.setGui(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPunktacja = new javax.swing.JTextArea();
        jCheckBoxDie0 = new javax.swing.JCheckBox();
        jCheckBoxDie1 = new javax.swing.JCheckBox();
        jCheckBoxDie2 = new javax.swing.JCheckBox();
        jCheckBoxDie3 = new javax.swing.JCheckBox();
        jCheckBoxDie4 = new javax.swing.JCheckBox();
        jTextFieldDie0 = new javax.swing.JTextField();
        jTextFieldDie1 = new javax.swing.JTextField();
        jTextFieldDie2 = new javax.swing.JTextField();
        jTextFieldDie3 = new javax.swing.JTextField();
        jTextFieldDie4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRanking = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxUklady = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMnoznik = new javax.swing.JTextField();
        jLabelPlayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaPunktacja.setEditable(false);
        jTextAreaPunktacja.setColumns(20);
        jTextAreaPunktacja.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPunktacja);

        jCheckBoxDie0.setText("zablokuj");
        jCheckBoxDie0.setEnabled(false);

        jCheckBoxDie1.setText("zablokuj");
        jCheckBoxDie1.setEnabled(false);

        jCheckBoxDie2.setText("zablokuj");
        jCheckBoxDie2.setEnabled(false);

        jCheckBoxDie3.setText("zablokuj");
        jCheckBoxDie3.setEnabled(false);

        jCheckBoxDie4.setText("zablokuj");
        jCheckBoxDie4.setEnabled(false);

        jTextFieldDie0.setEditable(false);
        jTextFieldDie0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDie0ActionPerformed(evt);
            }
        });

        jTextFieldDie1.setEditable(false);

        jTextFieldDie2.setEditable(false);

        jTextFieldDie3.setEditable(false);

        jTextFieldDie4.setEditable(false);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField6.setEnabled(false);

        jTextAreaRanking.setEditable(false);
        jTextAreaRanking.setColumns(20);
        jTextAreaRanking.setRows(5);
        jTextAreaRanking.setPreferredSize(new java.awt.Dimension(150, 90));
        jScrollPane2.setViewportView(jTextAreaRanking);

        jLabel1.setText("Ranking");

        jComboBoxUklady.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "1 - jedynki", "2 - dwojki", "3 - trojki", "4 - czworki", "5 - piatki", "6 - szóstki", "3ki - trojki", "4ki - czwórki", "ful - ful", "ms - mały strit", "ds - duzy strit", "g - general", "sz - szansa", "par - par", "npar - npar" }));
        jComboBoxUklady.setEnabled(false);
        jComboBoxUklady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUkladyActionPerformed(evt);
            }
        });

        jLabel3.setText("x");

        jTextFieldMnoznik.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldDie2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDie1)
                                    .addComponent(jTextFieldDie0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDie4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDie3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBoxDie0)
                                    .addComponent(jCheckBoxDie1)
                                    .addComponent(jCheckBoxDie2)
                                    .addComponent(jCheckBoxDie3)
                                    .addComponent(jCheckBoxDie4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxUklady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMnoznik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDie0)
                            .addComponent(jTextFieldDie0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDie1)
                            .addComponent(jTextFieldDie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDie2)
                            .addComponent(jTextFieldDie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDie3)
                            .addComponent(jTextFieldDie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxDie4)
                            .addComponent(jTextFieldDie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabelPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUklady, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMnoznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDie0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDie0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDie0ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        synchronized(this){
            notify();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxUkladyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUkladyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUkladyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DiceGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxDie0;
    private javax.swing.JCheckBox jCheckBoxDie1;
    private javax.swing.JCheckBox jCheckBoxDie2;
    private javax.swing.JCheckBox jCheckBoxDie3;
    private javax.swing.JCheckBox jCheckBoxDie4;
    private javax.swing.JComboBox jComboBoxUklady;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPlayer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaPunktacja;
    private javax.swing.JTextArea jTextAreaRanking;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldDie0;
    private javax.swing.JTextField jTextFieldDie1;
    private javax.swing.JTextField jTextFieldDie2;
    private javax.swing.JTextField jTextFieldDie3;
    private javax.swing.JTextField jTextFieldDie4;
    private javax.swing.JTextField jTextFieldMnoznik;
    // End of variables declaration//GEN-END:variables

    public void setLabel(String text){
        jLabel2.setText(text);
    }
    
    public void setRanking(String text){
        jTextAreaRanking.setText(text);
    }
    
    public void setPunktacja(String text){
        jTextAreaPunktacja.setText(text);
    }
    
    public void setDice(int[] dice){
        jTextFieldDie0.setText(Integer.toString(dice[0]));
        jTextFieldDie1.setText(Integer.toString(dice[1]));
        jTextFieldDie2.setText(Integer.toString(dice[2]));
        jTextFieldDie3.setText(Integer.toString(dice[3]));
        jTextFieldDie4.setText(Integer.toString(dice[4]));
    }

    public void setPlayer(String text){
        jLabelPlayer.setText(text);
    }
    
    public synchronized int getInteger() throws InterruptedException{
        jTextField6.setEnabled(true);
        wait();
        jTextField6.setEnabled(false);
        int ret = Integer.parseInt(jTextField6.getText());
        jTextField6.setText("");
        return ret;
    }
    
    public synchronized String getString() throws InterruptedException{
        jTextField6.setEnabled(true);
        wait();
        jTextField6.setEnabled(false);
        String ret = jTextField6.getText();
        jTextField6.setText("");
        return ret;
    }

    public synchronized boolean[] getBlocked() throws InterruptedException{
        jCheckBoxDie0.setEnabled(true);
        jCheckBoxDie1.setEnabled(true);
        jCheckBoxDie2.setEnabled(true);
        jCheckBoxDie3.setEnabled(true);
        jCheckBoxDie4.setEnabled(true);
        wait();
        jCheckBoxDie0.setEnabled(false);
        jCheckBoxDie1.setEnabled(false);
        jCheckBoxDie2.setEnabled(false);
        jCheckBoxDie3.setEnabled(false);
        jCheckBoxDie4.setEnabled(false);
        
        boolean [] ret = new boolean [5];
        
        ret[0] = jCheckBoxDie0.isSelected();
        ret[1] = jCheckBoxDie1.isSelected();
        ret[2] = jCheckBoxDie2.isSelected();
        ret[3] = jCheckBoxDie3.isSelected();
        ret[4] = jCheckBoxDie4.isSelected();
        
        return ret;
    }

    public synchronized String getUklad() throws InterruptedException{
        jComboBoxUklady.setEnabled(true);
        jTextFieldMnoznik.setEnabled(true);
        wait();
        jComboBoxUklady.setEnabled(false);
        jTextFieldMnoznik.setEnabled(false);
        
//        System.out.println(
//                jComboBoxUklady.getSelectedItem().toString().substring(0,
//                  jComboBoxUklady.getSelectedItem().toString().indexOf(' ')
//                ) +
//                'x' +
//                jTextFieldMnoznik.getText()
//                );
        
        return jComboBoxUklady.getSelectedItem().toString().substring(0,
                  jComboBoxUklady.getSelectedItem().toString().indexOf(' ')
                ) +
                'x' +
                jTextFieldMnoznik.getText();
    }
}
